"""BenchHub Benchmark Ingestion, Schema, and Stratified Splitting Module."""

from __future__ import annotations

from .loader import (
    BenchHubError,
    BenchmarkLoader,
    DuplicatePolicy,
    DuplicateTaskError,
    SuiteLoadError,
    SuiteValidationError,
    load_benchmark_suite,
    load_suite,
    load_suite_from_dict,
    load_suite_from_directory,
    load_suite_from_file,
    load_suite_from_json_string,
    load_suite_from_list,
    load_suite_from_yaml_string,
    save_suite,
    save_suite_to_file,
    suite_to_dict,
    suite_to_json,
    suite_to_yaml,
)
from .schema import (
    ATIFTask,
    BehavioralTag,
    BenchmarkSuite,
    DifficultyLevel,
    VerificationSpec,
)
from .splitter import (
    DivergenceReport,
    MultidimensionalStratifiedSplitter,
    SplitResult,
    StratifiedSplit,
    StratifiedSplitter,
    calculate_divergence,
    chi_square_contingency,
    chi_square_divergence,
    compute_distribution_divergence,
    jensen_shannon_divergence,
    stratified_split,
)

__all__ = [
    # Schema
    "BehavioralTag",
    "DifficultyLevel",
    "VerificationSpec",
    "ATIFTask",
    "BenchmarkSuite",
    # Loader
    "BenchHubError",
    "SuiteLoadError",
    "DuplicateTaskError",
    "SuiteValidationError",
    "DuplicatePolicy",
    "BenchmarkLoader",
    "load_suite",
    "load_benchmark_suite",
    "load_suite_from_file",
    "load_suite_from_directory",
    "load_suite_from_dict",
    "load_suite_from_list",
    "load_suite_from_json_string",
    "load_suite_from_yaml_string",
    "save_suite",
    "save_suite_to_file",
    "suite_to_dict",
    "suite_to_json",
    "suite_to_yaml",
    # Splitter
    "StratifiedSplitter",
    "MultidimensionalStratifiedSplitter",
    "SplitResult",
    "StratifiedSplit",
    "DivergenceReport",
    "jensen_shannon_divergence",
    "chi_square_contingency",
    "calculate_divergence",
    "chi_square_divergence",
    "compute_distribution_divergence",
    "stratified_split",
]
